server:
  port: 10001

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      default-filters:
#        - Elapsed=true
#      default-filters:
#        - name: RequestRateLimiter
#          args:
#            key-resolver: "#{@remoteAddrKeyResolver}"
#            redis-rate-limiter:
#              replenishRate: 1
#              burstCapacity: 5
#            status: 401
      routes:
       - id: test
         uri: lb://REDSANDALWOOD-TEST
         order: 0
         predicates:
           - Path=/test/**
         filters:
           - StripPrefix=1
           - AddResponseHeader=X-Response-Default-Foo, Default-Bar
       - id: user
         uri: lb://REDSANDALWOOD-USER
         order: 0
         predicates:
          - Path=/user/**
         filters:
           - StripPrefix=1
           - AddResponseHeader=X-Response-Default-Foo, Default-Bar
           # -------
#           - name: RequestRateLimiter
#             args:
#               key-resolver: "#{@remoteAddrKeyResolver}"
#               redis-rate-limiter:
#                replenishRate: 1
#                burstCapacity: 5
#               status: 401
           # -------
  # -------
  sleuth:
    web:
      client:
        enabled: true #打开sleuth客户端功能
    sampler:
      probability: 1.0 #将采样比设置为1，全部采样，默认为0.1
    zipkin:
      base-url: http://localhost:9411/ #指定链路追踪服务地址

#  redis:
#    host: localhost
#    port: 6379
#    database: 0
  # -------
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: debug
    com.springcloud.cloudgateway.filter: debug